// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRestore() {
  return window['go']['main']['App']['CancelRestore']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearBackupLock() {
  return window['go']['main']['App']['ClearBackupLock']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteDestination(arg1) {
  return window['go']['main']['App']['DeleteDestination'](arg1);
}

export function DeleteJob(arg1) {
  return window['go']['main']['App']['DeleteJob'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DismissBackupCheckpoint(arg1) {
  return window['go']['main']['App']['DismissBackupCheckpoint'](arg1);
}

export function EstimatePath(arg1, arg2) {
  return window['go']['main']['App']['EstimatePath'](arg1, arg2);
}

export function ExportConfigDialog() {
  return window['go']['main']['App']['ExportConfigDialog']();
}

export function ExportHistoryDialog() {
  return window['go']['main']['App']['ExportHistoryDialog']();
}

export function FetchFingerprint(arg1) {
  return window['go']['main']['App']['FetchFingerprint'](arg1);
}

export function GetBackupCheckpoint(arg1) {
  return window['go']['main']['App']['GetBackupCheckpoint'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetContactInfo() {
  return window['go']['main']['App']['GetContactInfo']();
}

export function GetDefaultExclusions() {
  return window['go']['main']['App']['GetDefaultExclusions']();
}

export function GetDiagnostics() {
  return window['go']['main']['App']['GetDiagnostics']();
}

export function GetExecutionState() {
  return window['go']['main']['App']['GetExecutionState']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetHostname() {
  return window['go']['main']['App']['GetHostname']();
}

export function GetLastProgress() {
  return window['go']['main']['App']['GetLastProgress']();
}

export function GetLastSuccessfulBackup() {
  return window['go']['main']['App']['GetLastSuccessfulBackup']();
}

export function GetNextScheduledRun() {
  return window['go']['main']['App']['GetNextScheduledRun']();
}

export function GetPBSWebURL(arg1) {
  return window['go']['main']['App']['GetPBSWebURL'](arg1);
}

export function GetServiceStatus() {
  return window['go']['main']['App']['GetServiceStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HasSMTPPassword() {
  return window['go']['main']['App']['HasSMTPPassword']();
}

export function ImportConfigDialog() {
  return window['go']['main']['App']['ImportConfigDialog']();
}

export function InstallService() {
  return window['go']['main']['App']['InstallService']();
}

export function IsBackupRunning() {
  return window['go']['main']['App']['IsBackupRunning']();
}

export function IsRestoreRunning() {
  return window['go']['main']['App']['IsRestoreRunning']();
}

export function IsStopping() {
  return window['go']['main']['App']['IsStopping']();
}

export function ListDestinations() {
  return window['go']['main']['App']['ListDestinations']();
}

export function ListJobs() {
  return window['go']['main']['App']['ListJobs']();
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function ListSnapshotFiles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListSnapshotFiles'](arg1, arg2, arg3, arg4);
}

export function ListSnapshots(arg1) {
  return window['go']['main']['App']['ListSnapshots'](arg1);
}

export function ListVolumeFolders(arg1) {
  return window['go']['main']['App']['ListVolumeFolders'](arg1);
}

export function ListVolumes() {
  return window['go']['main']['App']['ListVolumes']();
}

export function OpenDataFolder() {
  return window['go']['main']['App']['OpenDataFolder']();
}

export function OpenTelegramContact() {
  return window['go']['main']['App']['OpenTelegramContact']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PickRestoreFolder() {
  return window['go']['main']['App']['PickRestoreFolder']();
}

export function RestartService() {
  return window['go']['main']['App']['RestartService']();
}

export function RestoreBatch(arg1) {
  return window['go']['main']['App']['RestoreBatch'](arg1);
}

export function RestoreFile(arg1) {
  return window['go']['main']['App']['RestoreFile'](arg1);
}

export function RestoreFolder(arg1) {
  return window['go']['main']['App']['RestoreFolder'](arg1);
}

export function ResumeBackup(arg1) {
  return window['go']['main']['App']['ResumeBackup'](arg1);
}

export function RunHealthCheck() {
  return window['go']['main']['App']['RunHealthCheck']();
}

export function RunQuickBackup(arg1) {
  return window['go']['main']['App']['RunQuickBackup'](arg1);
}

export function SaveDestination(arg1, arg2) {
  return window['go']['main']['App']['SaveDestination'](arg1, arg2);
}

export function SaveJob(arg1, arg2) {
  return window['go']['main']['App']['SaveJob'](arg1, arg2);
}

export function SaveJobAndRun(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveJobAndRun'](arg1, arg2, arg3);
}

export function SaveServer(arg1, arg2) {
  return window['go']['main']['App']['SaveServer'](arg1, arg2);
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function ServerSecretReady(arg1) {
  return window['go']['main']['App']['ServerSecretReady'](arg1);
}

export function StartBackup(arg1) {
  return window['go']['main']['App']['StartBackup'](arg1);
}

export function StartForceFullBackup(arg1) {
  return window['go']['main']['App']['StartForceFullBackup'](arg1);
}

export function StartService() {
  return window['go']['main']['App']['StartService']();
}

export function StopBackup(arg1) {
  return window['go']['main']['App']['StopBackup'](arg1);
}

export function StopService() {
  return window['go']['main']['App']['StopService']();
}

export function TestDestinationByID(arg1) {
  return window['go']['main']['App']['TestDestinationByID'](arg1);
}

export function TestDestinationConnection(arg1, arg2) {
  return window['go']['main']['App']['TestDestinationConnection'](arg1, arg2);
}

export function TestSMTP(arg1, arg2) {
  return window['go']['main']['App']['TestSMTP'](arg1, arg2);
}

export function TestServerByID(arg1) {
  return window['go']['main']['App']['TestServerByID'](arg1);
}

export function TestServerConnection(arg1, arg2) {
  return window['go']['main']['App']['TestServerConnection'](arg1, arg2);
}

export function UninstallService() {
  return window['go']['main']['App']['UninstallService']();
}
