// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CancelRestore():Promise<void>;

export function CheckForUpdates():Promise<models.UpdateInfo>;

export function ClearBackupLock():Promise<models.ConnectionTestResult>;

export function ClearHistory():Promise<void>;

export function DeleteDestination(arg1:string):Promise<void>;

export function DeleteJob(arg1:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function DismissBackupCheckpoint(arg1:string):Promise<void>;

export function EstimatePath(arg1:string,arg2:Array<string>):Promise<models.PathEstimate>;

export function ExportConfigDialog():Promise<string>;

export function ExportHistoryDialog():Promise<string>;

export function FetchFingerprint(arg1:string):Promise<string>;

export function GetBackupCheckpoint(arg1:string):Promise<models.BackupCheckpoint>;

export function GetConfig():Promise<models.Config>;

export function GetConfigPath():Promise<string>;

export function GetContactInfo():Promise<models.ContactInfo>;

export function GetDefaultExclusions():Promise<Array<string>>;

export function GetDiagnostics():Promise<Record<string, string>>;

export function GetExecutionState():Promise<models.ExecutionState>;

export function GetHistory():Promise<Array<models.JobRunRecord>>;

export function GetHostname():Promise<string>;

export function GetLastProgress():Promise<models.ProgressEvent>;

export function GetLastSuccessfulBackup():Promise<models.LastBackupInfo>;

export function GetNextScheduledRun():Promise<string>;

export function GetPBSWebURL(arg1:string):Promise<string>;

export function GetServiceStatus():Promise<models.ServiceStatus>;

export function GetSettings():Promise<models.AppSettings>;

export function GetVersion():Promise<string>;

export function HasSMTPPassword():Promise<boolean>;

export function ImportConfigDialog():Promise<string>;

export function InstallService():Promise<models.ServiceActionResult>;

export function IsBackupRunning():Promise<boolean>;

export function IsRestoreRunning():Promise<boolean>;

export function IsStopping():Promise<boolean>;

export function ListDestinations():Promise<Array<models.BackupDestination>>;

export function ListJobs():Promise<Array<models.BackupJob>>;

export function ListServers():Promise<Array<models.PBSServer>>;

export function ListSnapshotFiles(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<models.SnapshotFile>>;

export function ListSnapshots(arg1:string):Promise<Array<models.SnapshotInfo>>;

export function ListVolumeFolders(arg1:string):Promise<Array<models.VolumeFolder>>;

export function ListVolumes():Promise<Array<string>>;

export function OpenDataFolder():Promise<void>;

export function OpenTelegramContact():Promise<void>;

export function PickFolder():Promise<string>;

export function PickRestoreFolder():Promise<string>;

export function ReloadStoreFromDisk():Promise<void>;

export function RestartService():Promise<models.ServiceActionResult>;

export function RestoreBatch(arg1:models.RestoreBatchRequest):Promise<void>;

export function RestoreFile(arg1:models.RestoreRequest):Promise<void>;

export function RestoreFolder(arg1:models.RestoreFolderRequest):Promise<void>;

export function ResumeBackup(arg1:string):Promise<void>;

export function RunHealthCheck():Promise<models.HealthReport>;

export function RunQuickBackup(arg1:models.QuickBackupRequest):Promise<void>;

export function SaveDestination(arg1:models.BackupDestination,arg2:string):Promise<void>;

export function SaveJob(arg1:models.BackupJob,arg2:string):Promise<void>;

export function SaveJobAndRun(arg1:models.BackupJob,arg2:string,arg3:boolean):Promise<void>;

export function SaveServer(arg1:models.PBSServer,arg2:string):Promise<void>;

export function SaveSettings(arg1:models.AppSettings,arg2:string):Promise<void>;

export function ServerSecretReady(arg1:string):Promise<boolean>;

export function StartBackup(arg1:string):Promise<void>;

export function StartForceFullBackup(arg1:string):Promise<void>;

export function StartService():Promise<models.ServiceActionResult>;

export function StopBackup(arg1:string):Promise<void>;

export function StopService():Promise<models.ServiceActionResult>;

export function TestDestinationByID(arg1:string):Promise<models.ConnectionTestResult>;

export function TestDestinationConnection(arg1:models.BackupDestination,arg2:string):Promise<models.ConnectionTestResult>;

export function TestSMTP(arg1:models.AppSettings,arg2:string):Promise<models.ConnectionTestResult>;

export function TestServerByID(arg1:string):Promise<models.ConnectionTestResult>;

export function TestServerConnection(arg1:models.PBSServer,arg2:string):Promise<models.ConnectionTestResult>;

export function UninstallService():Promise<models.ServiceActionResult>;
